### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by RUSshy** [Temtaime/stb#1]
Hi,

I try to build with ``DFLAGS="-m32mscoff" dub run :skeletal_animation --arch=x86 --build=debug``

But i get this:

```
stb-1.7.5\stb\lib\stb.lib
 Error 43: Not a Valid Library File
Error: linker exited with status 1
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

This works: ``dub run :skeletal_animation --arch=x86_64 --build=debug``  but i need x86 :/

**Comment by Temtaime** [comment]
Hello.
Seems that dmd's still using optlink ?
Do you have installed msvc environment properly ?

**Comment by RUSshy** [comment]
I have vs 2019

But with ``DFLAGS="-m32mscoff"`` it should remove requirement for msvc

**Comment by Temtaime** [comment]
Hello.
I set up CI and it doesn't show troubles while testing on x86 windows.
https://github.com/Temtaime/stb/runs/2047878243?check_suite_focus=true
Seems that there's a trouble with your setup.
Close the issue if it's resolved
